// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (title, description, published_at, url, feed_id)
VALUES($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, title, description, published_at, url, feed_id
`

type CreatePostParams struct {
	Title       string
	Description sql.NullString
	PublishedAt time.Time
	Url         string
	FeedID      int64
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.Url,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.Url,
		&i.FeedID,
	)
	return i, err
}

const getPostsByFeedFollow = `-- name: GetPostsByFeedFollow :many
SELECT id, created_at, updated_at, title, description, published_at, url, feed_id FROM posts WHERE feed_id = ANY($1::int[]) ORDER BY published_at DESC LIMIT $2
`

type GetPostsByFeedFollowParams struct {
	Column1 []int32
	Limit   int32
}

func (q *Queries) GetPostsByFeedFollow(ctx context.Context, arg GetPostsByFeedFollowParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByFeedFollow, pq.Array(arg.Column1), arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.PublishedAt,
			&i.Url,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
